# Generated by Django 5.2.7 on 2025-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact or Phone number', max_length=15, null=True),
        ),
    ]
