# Generated by Django 5.2.7 on 2025-10-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Range Report')], default='daily', max_length=10)),
                ('start_date', models.DateField(help_text='Start date for the report')),
                ('end_date', models.DateField(help_text='End date for the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(blank=True, help_text='Path to the generated report file', null=True, upload_to='attendance_reports/%Y/%m/')),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for all-courses report', null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.course')),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'ordering': ['created_at'],
            },
        ),
    ]
